language: android

android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-5be876d5

jdk: oraclejdk7

branches:
  except:
    - master
    - gh-pages

notifications:
  email:
    - halysongoncalves@gmail.com
