language: android

jdk: oraclejdk7

android:
  components:
    - build-tools-23.0.1
    - android-23

branches:
  except:
    - master
    - gh-pages

notifications:
  email:
    - halysongoncalves@gmail.com

script:
    - ./gradlew assemble